### ISSUE TITLE
Fails to start when I run with -p option

### ISSUE THREAD

**Issue by salboaie** [nickstenning/docker-slapd#4]
Hi! Nice project! But.. I have an issue with your  docker image. It works when I run it like this:
docker run -v /data/ldap:/var/lib/ldap \
           -e LDAP_DOMAIN=usmed \
           -e LDAP_ORGANISATION="USMED project" \
           -e LDAP_ROOTPASS=mysecret \
           -d nickstenning/slapd

But when I add -p line like below I get an error:

docker run -v /data/ldap:/var/lib/ldap \
           -e LDAP_DOMAIN=usmed \
           -e LDAP_ORGANISATION="USMED project" \
           -e LDAP_ROOTPASS=mysecret \
       -p 389:389\
           -d nickstenning/slapd

The error:
199540f01d324a5c5b2b37e661d26dd4333550bec1e22d4470952e50d5ad28f6
2015/01/23 02:57:27 Error response from daemon: Cannot start container 199540f01d324a5c5b2b37e661d26dd4333550bec1e22d4470952e50d5ad28f6:  (exit status 1)

Without -p line, the container is pretty much useless, isn't it ? 
Thank you,
Sinica

**Comment by ludwikbukowski** [comment]
It works for me. Have you tried adding the port line at the begining?
For me worked version:
```
docker run  \
           -p 389:389 \
           -e LDAP_DOMAIN=mycorp.com \
           -e LDAP_ORGANISATION="My Mega Corporation" \
           -e LDAP_ROOTPASS=s3cr3tpassw0rd \
           -d nickstenning/slapd
```

**Comment by marcbihlmaier** [comment]
works for me as well.
@salboaie  maybe the port 389 is used by another Container on your host?

**Comment by nickstenning** [comment]
This looks like a problem with your environment or your docker installation, not with this image. Feel free to reopen if you there's reason to believe it's a problem with this image.
