### ISSUE TITLE
persistent database fails because of auth problems

### ISSUE THREAD

**Issue by rdxmb** [nickstenning/docker-slapd#9]
using persistent data (e.g. in docker-compose) with 

```
      - type: volume
        source: ldapdata
        target: /var/lib/ldap
```

restarting the container/service
---> auth fails

reason:
slapd writes the auth data of the admin user within /etc/ldap

so persistent data within /etc/ldap is also needed:

```
      - type: volume
        source: ldapconfig
        target: /etc/ldap
```

This should be added in Dockerfile and README.md

Greetings, rdxmb

**Comment by rdxmb** [comment]
The key is to have either config *and* data within the container - or nothing.
Splitting these will cause errors.

**Comment by nickstenning** [comment]
Right, understood. I can take a look at unifying this into one volume for a future update.

**Comment by rdxmb** [comment]
Feel free. Having this documented in that way would have been enough for my case. Greetings.
